/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns service status. No authentication required.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtain access token
         * @description Exchange credentials for a JWT access token and refresh token.
         *     Supports password grant (email/password), refresh_token grant, and
         *     OAuth2 authorization_code grant (Google, Azure AD, Okta).
         */
        post: operations["getToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Exchange a valid refresh token for a new access token.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke tokens
         * @description Revoke the current access token and refresh token (adds JTI to Redis denylist).
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Return the authenticated user's profile and role.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cloud accounts
         * @description Return all active cloud accounts for the current tenant.
         *     Includes `last_sync_at` timestamp and `record_count` for each account.
         *     Requires `viewer` role or higher.
         */
        get: operations["listAccounts"];
        put?: never;
        /**
         * Create a cloud account connection
         * @description Create a new cloud account connection.
         *     Validates credentials by making a test API call to the provider before saving.
         *     Raw credentials are never stored; only a `credentials_ref` is kept.
         *     Requires `admin` role.
         */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a cloud account
         * @description Soft-delete a cloud account (sets `status = 'inactive'`).
         *     Writes an audit log entry.
         *     Requires `admin` role.
         */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a billing file
         * @description Upload a billing file for ingestion. Supported formats:
         *     - **AWS CUR** (CSV, optionally gzip-compressed) — auto-detected from filename
         *     - **Azure Cost Management** export (CSV)
         *     - **GCP BigQuery** billing export (JSON)
         *     - **FOCUS 1.0** (CSV or Parquet) — validated against the FOCUS schema
         *
         *     If the file contains validation errors, they are returned without ingesting any records.
         *     Requires `analyst` role or higher.
         */
        post: operations["uploadBillingFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/sync/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger async account sync
         * @description Start a background sync job for the specified cloud account.
         *     The sync fetches billing data directly from the provider API and ingests it.
         *     Returns a `job_id` immediately; poll `/ingest/sync/{job_id}/status` for progress.
         *     Requires `engineer` or `admin` role.
         */
        post: operations["triggerSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/sync/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sync job status
         * @description Poll the status of an async sync job.
         *     Job status is stored in Redis with a 24-hour TTL.
         */
        get: operations["getSyncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query FOCUS records
         * @description Query normalised FOCUS 1.0 billing records for the current tenant.
         *     Supports filtering by provider, region, service, date range, and tags.
         *     Full implementation in Session 3.
         */
        get: operations["listRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{id}/enrichment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get enrichment for a FOCUS record
         * @description Return GHG and water enrichment data for a specific FOCUS record. Implemented in Session 3.
         */
        get: operations["getRecordEnrichment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrichment/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start enrichment job
         * @description Trigger carbon and water enrichment for a tenant's FOCUS records.
         *     Runs as a background task; poll `/enrichment/status/{job_id}` for progress.
         *
         *     **Modes:**
         *     - `incremental` (default): only enrich records without an existing enriched_record.
         *     - `full`: re-enrich all records (use after methodology updates).
         *
         *     **Required role:** `engineer` or above.
         */
        post: operations["runEnrichment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrichment/status/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get enrichment job status
         * @description Poll the progress of an enrichment job by job_id.
         *     Job state is stored in Redis with a 24-hour TTL.
         */
        get: operations["getEnrichmentStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrichment/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get enrichment summary
         * @description Return aggregated carbon and water statistics for the current tenant.
         *     Includes total CO2e, Scope 3 breakdown, water consumption, and coverage percentage.
         *
         *     **Required role:** `viewer` or above.
         */
        get: operations["getEnrichmentSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recommendations
         * @description List actionable GreenOps recommendations with optional filters and sorting.
         *     Use `mode=sustainability` to sort by carbon impact instead of cost.
         */
        get: operations["listRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run recommendation engine
         * @description Trigger the recommendation engine for the current tenant as a background task.
         *     Weights must sum to 1.0. Returns a job ID immediately (HTTP 202).
         */
        post: operations["runRecommendations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommendation opportunity summary
         * @description Return aggregated cost, carbon, and water opportunity statistics.
         */
        get: operations["recommendationsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/{recommendation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update recommendation status
         * @description Update the status of a recommendation (implement, dismiss, snooze).
         */
        patch: operations["updateRecommendation"];
        trace?: never;
    };
    "/reports/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Multi-dimensional overview report
         * @description Return cost, carbon, and water totals with month-over-month changes,
         *     provider breakdown, service category breakdown, and top 10 resources by CO2e.
         */
        get: operations["overviewReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/carbon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GHG Protocol carbon report
         * @description Return a GHG Protocol-aligned carbon report with time series (Scope 2 + Scope 3),
         *     regional breakdown, and Scope 3 category detail with confidence distribution.
         */
        get: operations["carbonReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/water": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Water consumption report
         * @description Return water consumption with regional breakdown (WRI Aqueduct stress scores),
         *     service category breakdown, and high-stress region alerts.
         */
        get: operations["waterReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Holt-Winters metric forecast
         * @description Return Holt-Winters exponential smoothing forecasts for one or more metrics.
         *     Includes 80% confidence intervals and 14-day holdout MAE.
         *
         *     **Supported metrics:** cost_usd, total_co2e_kg, water_litres, water_stress_adjusted_litres
         */
        get: operations["forecastReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/natural-language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Natural language query
         * @description Translate a natural language question into a SQL query and execute it
         *     against the enriched billing data. Returns the generated SQL, results,
         *     and 3 follow-up question suggestions.
         *
         *     **Required role:** analyst or above.
         */
        post: operations["naturalLanguageQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/cost-carbon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost vs carbon report
         * @description Correlate cloud spend with carbon emissions by service and region.
         */
        get: operations["costCarbonReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List governance policy rules
         * @description Return active governance policy rules for the current tenant.
         */
        get: operations["listPolicies"];
        put?: never;
        /**
         * Create a policy rule
         * @description Create a new governance policy rule. Requires admin role.
         */
        post: operations["createPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List agent configurations
         * @description Return all agent configurations for the current tenant.
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update agent configuration
         * @description Update an agent's configuration. Requires admin role.
         */
        patch: operations["updateAgentConfig"];
        trace?: never;
    };
    "/agents/{agent_type}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger manual agent run
         * @description Trigger an immediate manual run of the specified agent as a background task.
         */
        post: operations["triggerAgentRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List agent runs
         * @description Return paginated list of agent runs for the current tenant.
         */
        get: operations["listAgentRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get agent run detail
         * @description Return full agent run detail including all actions taken.
         */
        get: operations["getAgentRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/runs/{run_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a pending agent action
         * @description Approve a pending_approval action from an agent run. Requires engineer role.
         */
        post: operations["approveAgentAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description FOCUS 1.0 billing record (PascalCase field names per specification) */
        FocusRecord: {
            /**
             * Format: date-time
             * @description Start of the billing period (UTC)
             */
            BillingPeriodStart: string;
            /**
             * Format: date-time
             * @description End of the billing period (UTC)
             */
            BillingPeriodEnd: string;
            /**
             * @description FOCUS charge category
             * @enum {string}
             */
            ChargeCategory: "Usage" | "Purchase" | "Tax" | "Adjustment" | "Credit";
            /** @enum {string|null} */
            ChargeClass?: "Regular" | "Correction" | null;
            ChargeDescription?: string | null;
            /** @enum {string|null} */
            ChargeFrequency?: "One-Time" | "Recurring" | "Usage-Based" | null;
            /** Format: date-time */
            ChargePeriodStart?: string | null;
            /** Format: date-time */
            ChargePeriodEnd?: string | null;
            /** Format: double */
            ConsumedQuantity?: number | null;
            ConsumedUnit?: string | null;
            /** Format: double */
            ContractedCost?: number | null;
            /** Format: double */
            ContractedUnitPrice?: number | null;
            /**
             * Format: double
             * @description Effective cost in USD
             */
            EffectiveCost: number;
            InvoiceIssuerName: string;
            /** Format: double */
            ListCost?: number | null;
            /** Format: double */
            ListUnitPrice?: number | null;
            /** @enum {string|null} */
            PricingCategory?: "On-Demand" | "Commitment-Based" | "Spot" | "Other" | null;
            /** Format: double */
            PricingQuantity?: number | null;
            PricingUnit?: string | null;
            /** @description Cloud provider name (e.g. "Amazon Web Services") */
            ProviderName: string;
            PublisherName?: string | null;
            /** @description Provider region code (e.g. "us-east-1") */
            RegionId?: string | null;
            /** @description Human-readable region name */
            RegionName?: string | null;
            ResourceId?: string | null;
            ResourceName?: string | null;
            ResourceType?: string | null;
            /** @description High-level service category (e.g. "Compute", "Storage") */
            ServiceCategory: string;
            /** @description Provider service name (e.g. "Amazon EC2") */
            ServiceName: string;
            SkuId?: string | null;
            SkuPriceId?: string | null;
            /** @description AWS account ID / Azure subscription ID / GCP project ID */
            SubAccountId?: string | null;
            SubAccountName?: string | null;
            /** @description Resource tags as key-value pairs */
            Tags?: {
                [key: string]: string;
            } | null;
        };
        CloudCarbonRecord: components["schemas"]["FocusRecord"] & {
            /**
             * Format: double
             * @description GHG Protocol Scope 1 emissions (kgCO2eq)
             */
            scope1_co2e_kg?: number | null;
            /**
             * Format: double
             * @description Scope 2 location-based emissions (kgCO2eq)
             */
            scope2_co2e_kg_location?: number | null;
            /**
             * Format: double
             * @description Scope 2 market-based emissions (kgCO2eq)
             */
            scope2_co2e_kg_market?: number | null;
            /**
             * Format: double
             * @description Scope 3 Cat 1 — purchased goods and services / hardware manufacturing
             */
            scope3_cat1_co2e_kg?: number | null;
            /**
             * Format: double
             * @description Scope 3 Cat 3 — fuel and energy related activities
             */
            scope3_cat3_co2e_kg?: number | null;
            /**
             * Format: double
             * @description Scope 3 Cat 12 — end-of-life treatment
             */
            scope3_cat12_co2e_kg?: number | null;
            /** Format: double */
            scope3_total_co2e_kg?: number | null;
            /** @enum {string|null} */
            scope3_confidence?: "high" | "medium" | "low" | null;
            /** @description Reference to the methodology used (e.g. "boavizta-v2.3") */
            scope3_methodology_ref?: string | null;
            /**
             * Format: double
             * @description Total GHG emissions across all scopes (kgCO2eq)
             */
            total_co2e_kg?: number | null;
            /**
             * Format: double
             * @description Grid carbon intensity used for calculation (gCO2eq/kWh)
             */
            carbon_intensity_gco2_kwh?: number | null;
            /**
             * Format: double
             * @description Estimated electricity consumption (kWh)
             */
            estimated_kwh?: number | null;
            /** @description Underlying hardware family (e.g. "Intel Xeon Ice Lake") */
            hardware_family?: string | null;
            /**
             * Format: double
             * @description Fraction of physical host used by this resource (0.0–1.0)
             */
            resource_share?: number | null;
            /**
             * Format: double
             * @description Estimated water consumption (litres)
             */
            water_litres?: number | null;
            /**
             * Format: double
             * @description Water Usage Effectiveness applied (litres/kWh)
             */
            wue_litres_per_kwh?: number | null;
            /**
             * Format: double
             * @description WRI Aqueduct water stress score (0–5)
             */
            water_stress_score?: number | null;
            /**
             * Format: double
             * @description Water consumption adjusted for local water stress
             */
            water_stress_adjusted_litres?: number | null;
            /** @enum {string|null} */
            water_data_source?: "provider_disclosed" | "cooling_type_estimate" | null;
        };
        ValidationErrorDetail: {
            /** @description 1-indexed row number in the uploaded file */
            row?: number;
            /** @description FOCUS field name that failed validation */
            field?: string | null;
            /** @description Human-readable validation error message */
            message?: string;
        };
        IngestionResult: {
            /** @description Number of new records inserted */
            inserted: number;
            /** @description Number of existing records updated */
            updated: number;
            /** @description Number of records skipped (e.g. duplicates) */
            skipped?: number;
            /** @description Total records processed (inserted + updated) */
            total: number;
            /** @description Non-fatal processing errors */
            errors?: string[];
            /** @description Per-row validation errors (only present for FOCUS passthrough uploads) */
            validation_errors?: components["schemas"]["ValidationErrorDetail"][];
        };
        SyncJobResponse: {
            /** @example sync_started */
            status: string;
            /** Format: uuid */
            account_id: string;
            /** Format: uuid */
            job_id: string;
        };
        SyncJobStatus: {
            /** Format: uuid */
            job_id: string;
            /** Format: uuid */
            account_id?: string | null;
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed";
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            result?: components["schemas"]["IngestionResult"];
            error?: string | null;
        };
        CloudAccountCreate: {
            /** @description Human-readable account name */
            name: string;
            /** @enum {string} */
            provider: "aws" | "azure" | "gcp" | "alibaba";
            /** @description Provider account ID (AWS account ID, Azure subscription ID, GCP project ID) */
            account_identifier: string;
            /**
             * @description Provider-specific configuration:
             *     - AWS: `s3_bucket`, `s3_prefix`, `report_name`, `aws_region`
             *     - Azure: `subscription_id`, `resource_group`
             *     - GCP: `project_id`, `dataset_id`, `table_id`
             *     - Alibaba: `region_id`, `billing_cycle`
             */
            config?: {
                [key: string]: unknown;
            };
            /**
             * @description Provider credentials (stored securely as credentials_ref, never returned):
             *     - AWS: `aws_access_key_id`, `aws_secret_access_key`
             *     - Azure: `azure_tenant_id`, `azure_client_id`, `azure_client_secret`
             *     - GCP: `service_account_json`
             *     - Alibaba: `access_key_id`, `access_key_secret`
             */
            credentials?: {
                [key: string]: string;
            };
        };
        CloudAccountResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            name: string;
            /** @enum {string} */
            provider: "aws" | "azure" | "gcp" | "alibaba";
            account_identifier: string;
            /** @enum {string} */
            status: "active" | "inactive" | "error" | "pending";
            config?: {
                [key: string]: unknown;
            };
            /** @description Opaque reference to stored credentials (never the raw credentials) */
            credentials_ref?: string | null;
            /** Format: date-time */
            last_sync_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description Number of FOCUS records associated with this account */
            record_count?: number;
        };
        CloudAccountListResponse: {
            accounts: components["schemas"]["CloudAccountResponse"][];
            total: number;
        };
        TokenRequest: {
            /** @enum {string} */
            grant_type: "password" | "refresh_token" | "authorization_code";
            username?: string;
            /** Format: password */
            password?: string;
            refresh_token?: string;
            /** @description OAuth2 authorization code */
            code?: string;
            /**
             * @description OAuth2 provider (required for authorization_code grant)
             * @enum {string}
             */
            provider?: "google" | "azure_ad" | "okta";
        };
        TokenResponse: {
            access_token: string;
            /** @example bearer */
            token_type: string;
            /** @description Access token lifetime in seconds */
            expires_in: number;
            refresh_token?: string | null;
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name?: string | null;
            /** @enum {string} */
            role: "viewer" | "analyst" | "engineer" | "admin";
            /** Format: uuid */
            tenant_id?: string;
        };
        EnrichmentRunRequest: {
            /**
             * Format: uuid
             * @description Tenant UUID to enrich records for
             */
            tenant_id: string;
            /**
             * @description incremental: only enrich records without an existing enriched_record.
             *     full: re-enrich all records (use when methodology is updated).
             * @default incremental
             * @enum {string}
             */
            mode: "incremental" | "full";
            /** @description Version string to stamp on re-enriched records (full mode only) */
            enrichment_version?: string | null;
            /** @description Maximum records to process (incremental mode only; default 1000) */
            limit?: number | null;
        };
        EnrichmentRunResponse: {
            /** @description Job ID for status polling */
            job_id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @enum {string} */
            mode: "incremental" | "full";
            /** @example queued */
            status: string;
            /** Format: date-time */
            queued_at: string;
        };
        EnrichmentStatusResponse: {
            job_id: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed";
            /** @default 0 */
            processed: number;
            /** @default 0 */
            total: number;
            /** Format: double */
            pct?: number;
            /** @default 0 */
            failed: number;
            errors?: string[];
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: double */
            duration_seconds?: number | null;
        };
        EnrichmentSummaryResponse: {
            /** Format: uuid */
            tenant_id: string;
            /** @description Number of FOCUS records with enrichment data */
            total_records_enriched: number;
            /** @description Total FOCUS records for the tenant */
            total_focus_records: number;
            /**
             * Format: double
             * @description Percentage of FOCUS records with enrichment (0–100)
             */
            coverage_pct: number;
            /**
             * Format: double
             * @description Total carbon across all scopes (kg CO2e)
             */
            total_co2e_kg: number;
            /**
             * Format: double
             * @description Total Scope 3 carbon (kg CO2e)
             */
            total_scope3_co2e_kg: number;
            /**
             * Format: double
             * @description Scope 3 as percentage of total carbon
             */
            scope3_pct_of_total: number;
            /**
             * Format: double
             * @description Total water consumption (litres)
             */
            total_water_litres: number;
            /** Format: date-time */
            last_enriched_at?: string | null;
            enrichment_version?: string | null;
        };
        /** @description Carbon and water enrichment for a single FOCUS billing record */
        EnrichedRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            focus_record_id: string;
            /** Format: uuid */
            tenant_id: string;
            /**
             * Format: double
             * @description Scope 1 direct emissions (always 0 for cloud customers)
             */
            scope1_co2e_kg?: number;
            /**
             * Format: double
             * @description Scope 2 location-based electricity emissions (kg CO2e)
             */
            scope2_co2e_kg_location?: number;
            /**
             * Format: double
             * @description Scope 2 market-based electricity emissions (kg CO2e)
             */
            scope2_co2e_kg_market?: number;
            /**
             * Format: double
             * @description Scope 3 Cat1 — embodied carbon in hardware (kg CO2e)
             */
            scope3_cat1_co2e_kg?: number;
            /**
             * Format: double
             * @description Scope 3 Cat3 — upstream fuel and energy activities (kg CO2e)
             */
            scope3_cat3_co2e_kg?: number;
            /**
             * Format: double
             * @description Scope 3 Cat12 — end-of-life treatment of hardware (kg CO2e)
             */
            scope3_cat12_co2e_kg?: number;
            /**
             * Format: double
             * @description Total Scope 3 (Cat1 + Cat3 + Cat12) in kg CO2e
             */
            scope3_total_co2e_kg?: number;
            /**
             * @description Confidence level of the Scope 3 estimate
             * @enum {string}
             */
            scope3_confidence?: "high" | "medium" | "low";
            /** @description Methodology version reference string */
            scope3_methodology_ref?: string;
            /**
             * Format: double
             * @description Total carbon (Scope 1 + Scope 2 location + Scope 3) in kg CO2e
             */
            total_co2e_kg: number;
            /**
             * Format: double
             * @description Carbon intensity used for estimation (gCO2eq/kWh)
             */
            carbon_intensity_gco2_kwh?: number;
            /**
             * Format: double
             * @description Estimated energy consumption (kWh)
             */
            estimated_kwh?: number;
            /** @description Hardware family used for Scope 3 Cat1 estimation */
            hardware_family?: string | null;
            /**
             * Format: double
             * @description Fraction of the physical host attributed to this record
             */
            resource_share?: number | null;
            /**
             * Format: double
             * @description Estimated water consumption (litres)
             */
            water_litres?: number;
            /**
             * Format: double
             * @description Water Usage Effectiveness coefficient used (L/kWh)
             */
            wue_litres_per_kwh?: number;
            /**
             * Format: double
             * @description WRI Aqueduct water stress score (0–5)
             */
            water_stress_score?: number | null;
            /**
             * Format: double
             * @description Water consumption adjusted for regional water stress (litres)
             */
            water_stress_adjusted_litres?: number;
            /** @description Source of WUE data */
            water_data_source?: string;
            /** Format: date-time */
            enriched_at: string;
            enrichment_version?: string;
        };
        /** @description A single actionable GreenOps recommendation */
        RecommendationResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /**
             * @description Recommendation type. One of: rightsize, terminate_idle,
             *     schedule_off_hours, reserved_instance, region_migrate_carbon,
             *     green_region_shift
             */
            type: string;
            resource_id: string;
            provider: string;
            region: string;
            service_name: string;
            /**
             * Format: double
             * @description Estimated monthly cost saving (USD)
             */
            cost_impact_monthly_usd: number;
            /**
             * Format: double
             * @description Estimated monthly carbon reduction (kg CO2e)
             */
            co2e_impact_monthly_kg: number;
            /**
             * Format: double
             * @description Estimated monthly water reduction (litres)
             */
            water_impact_monthly_litres: number;
            /**
             * Format: double
             * @description Composite weighted impact score (0–1)
             */
            impact_score: number;
            /** Format: double */
            cost_weight_used?: number;
            /** Format: double */
            carbon_weight_used?: number;
            /** Format: double */
            water_weight_used?: number;
            /** @enum {string} */
            complexity: "low" | "medium" | "high";
            implementation_steps?: string[];
            methodology_notes?: string;
            /** @description True if a governance policy rule blocked this recommendation */
            policy_blocked?: boolean;
            policy_block_reason?: string | null;
            requires_approval?: boolean;
            /** @enum {string} */
            status: "open" | "implemented" | "dismissed" | "snoozed";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        RecommendationListResponse: {
            items: components["schemas"]["RecommendationResponse"][];
            total: number;
            page: number;
            page_size: number;
        };
        RecommendationRunRequest: {
            /**
             * Format: double
             * @default 0.6
             */
            cost_weight: number;
            /**
             * Format: double
             * @default 0.3
             */
            carbon_weight: number;
            /**
             * Format: double
             * @default 0.1
             */
            water_weight: number;
        };
        RecommendationRunResponse: {
            /** Format: uuid */
            job_id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @example queued */
            status: string;
            /** Format: date-time */
            queued_at: string;
        };
        RecommendationPatchRequest: {
            /** @enum {string} */
            status: "implemented" | "dismissed" | "snoozed" | "open";
            /** Format: date-time */
            snooze_until?: string | null;
        };
        RecommendationSummaryResponse: {
            open_count?: number;
            /** Format: double */
            total_cost_opportunity_usd?: number;
            /** Format: double */
            total_co2e_opportunity_kg?: number;
            /** Format: double */
            total_water_opportunity_litres?: number;
            by_type?: {
                type?: string;
                count?: number;
                cost_usd?: number;
                co2e_kg?: number;
            }[];
            by_provider?: {
                provider?: string;
                count?: number;
                cost_usd?: number;
                co2e_kg?: number;
            }[];
        };
        OverviewReportResponse: {
            period?: {
                /** Format: date */
                start?: string;
                /** Format: date */
                end?: string;
            };
            /** Format: double */
            total_cost_usd?: number;
            /** Format: double */
            total_co2e_kg?: number;
            /** Format: double */
            scope3_co2e_kg?: number;
            /** Format: double */
            scope3_pct?: number;
            /** Format: double */
            total_water_litres?: number;
            /** Format: double */
            water_stress_adjusted_litres?: number;
            /**
             * Format: double
             * @description kg CO2e per $1000 spend
             */
            carbon_efficiency?: number;
            /**
             * Format: double
             * @description Month-over-month cost change (%)
             */
            cost_mom_pct?: number;
            /**
             * Format: double
             * @description Month-over-month carbon change (%)
             */
            co2e_mom_pct?: number;
            /**
             * Format: double
             * @description Month-over-month water change (%)
             */
            water_mom_pct?: number;
            by_provider?: Record<string, never>[];
            by_service_category?: Record<string, never>[];
            top_resources_by_co2e?: Record<string, never>[];
        };
        CarbonReportResponse: {
            period?: {
                /** Format: date */
                start?: string;
                /** Format: date */
                end?: string;
                /** @enum {string} */
                granularity?: "daily" | "weekly" | "monthly";
            };
            time_series?: {
                /** Format: date */
                date?: string;
                scope1?: number;
                scope2_location?: number;
                scope2_market?: number;
                scope3_total?: number;
                total?: number;
            }[];
            by_region?: Record<string, never>[];
            scope3_breakdown?: {
                cat1_embodied?: number;
                cat3_upstream?: number;
                cat12_eol?: number;
                total?: number;
                confidence_distribution?: Record<string, never>;
            };
        };
        WaterReportResponse: {
            period?: Record<string, never>;
            /** Format: double */
            total_water_litres?: number;
            /** Format: double */
            total_water_stress_adjusted_litres?: number;
            by_region?: Record<string, never>[];
            by_service_category?: Record<string, never>[];
            high_stress_regions?: Record<string, never>[];
        };
        /** @description Forecast results keyed by metric name */
        ForecastResponse: {
            [key: string]: components["schemas"]["ForecastResult"];
        };
        NLQueryRequest: {
            /** @example Which AWS regions have the highest carbon intensity this month? */
            question: string;
        };
        NLQueryResponse: {
            question: string;
            /** @description Generated SQL query */
            sql?: string | null;
            /** @description Query result rows */
            results?: Record<string, never>[] | null;
            row_count: number;
            /** @description 3 follow-up question suggestions */
            suggestions: string[];
            /** @description False if the question cannot be answered with available data */
            supported: boolean;
            error?: string | null;
        };
        AgentConfigResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            agent_type: "anomaly_detector" | "carbon_spike_monitor" | "rightsizing_agent" | "idle_reaper" | "green_scheduler";
            enabled: boolean;
            /** @description When true, agent analyses and notifies but does not take infrastructure actions */
            dry_run: boolean;
            /** @description Cron expression for scheduled runs (e.g. "0 0 * * *") */
            schedule_cron: string | null;
            /** @description Agent-specific configuration parameters */
            config?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            last_run_at: string | null;
            /** @enum {string|null} */
            last_run_status: "running" | "completed" | "failed" | null;
            last_run_findings?: number | null;
        };
        AgentConfigPatchRequest: {
            enabled?: boolean;
            dry_run?: boolean;
            schedule_cron?: string | null;
            config?: {
                [key: string]: unknown;
            };
        };
        ManualRunRequest: {
            /**
             * @description When true, agent will not take infrastructure actions
             * @default true
             */
            dry_run: boolean;
            /** @description Optional per-run config overrides */
            config_override?: {
                [key: string]: unknown;
            };
        };
        ManualRunResponse: {
            /** Format: uuid */
            run_id: string;
            agent_type: string;
            /** @enum {string} */
            status: "running";
            dry_run: boolean;
            /** Format: date-time */
            started_at: string;
        };
        AgentRunResponse: {
            /** Format: uuid */
            id: string;
            agent_type: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed";
            dry_run: boolean;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            duration_seconds?: number | null;
            findings_count?: number | null;
            actions_taken?: number | null;
            actions_pending_approval?: number | null;
            error_message?: string | null;
            /** @description List of findings (anomalies, recommendations, etc.) */
            findings?: Record<string, never>[];
            /** @description List of actions taken or proposed */
            actions?: Record<string, never>[];
        };
        AgentRunListResponse: {
            items: components["schemas"]["AgentRunResponse"][];
            total: number;
            limit: number;
            offset: number;
        };
        ApproveActionRequest: {
            /** Format: uuid */
            action_id: string;
            notes?: string | null;
        };
        ApproveActionResponse: {
            /** Format: uuid */
            action_id: string;
            /** @enum {string} */
            status: "executing" | "completed" | "failed";
            approved_by: string;
            /** Format: date-time */
            approved_at: string;
            result?: Record<string, never> | null;
        };
        ErrorResponse: {
            detail: string | Record<string, never>[];
        };
        PolicyRule: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id?: string;
            /** @description Human-readable policy rule name */
            name: string;
            description?: string | null;
            /** @enum {string} */
            rule_type: "exclude_region" | "min_co2e_threshold" | "require_approval" | "water_stress_block";
            /** @description Rule DSL condition (e.g. {"region": "cn-north-1"}) */
            condition: {
                [key: string]: unknown;
            };
            /** @default true */
            active: boolean;
            /** Format: uuid */
            created_by?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string | null;
        };
        PolicyRuleCreate: {
            name: string;
            description?: string | null;
            /** @enum {string} */
            rule_type: "exclude_region" | "min_co2e_threshold" | "require_approval" | "water_stress_block";
            condition: {
                [key: string]: unknown;
            };
            /** @default true */
            active: boolean;
        };
        ForecastResult: {
            /** @description Metric name (e.g. cost_usd, total_co2e_kg) */
            metric: string;
            dates: string[];
            predicted: number[];
            lower_80: number[];
            upper_80: number[];
            /**
             * Format: double
             * @description Mean absolute error on 14-day holdout
             */
            model_mae: number;
            data_points_used: number;
            horizon_days: number;
            /** Format: date-time */
            generated_at?: string | null;
        };
        AuthToken: components["schemas"]["TokenResponse"];
        User: components["schemas"]["UserResponse"];
        CloudAccount: components["schemas"]["CloudAccountResponse"];
        Recommendation: components["schemas"]["RecommendationResponse"];
        RecommendationSummary: components["schemas"]["RecommendationSummaryResponse"];
        OverviewReport: components["schemas"]["OverviewReportResponse"];
        CarbonReport: components["schemas"]["CarbonReportResponse"];
        WaterReport: components["schemas"]["WaterReportResponse"];
        NLQueryResult: components["schemas"]["NLQueryResponse"];
        AgentConfig: components["schemas"]["AgentConfigResponse"];
        AgentRun: components["schemas"]["AgentRunResponse"];
    };
    responses: {
        /** @description JWT missing or invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Insufficient role for this operation */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Requested resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request validation failed */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Page number for pagination */
        PageParam: number;
        /** @description Number of items per page */
        PageSizeParam: number;
        /** @description Cloud account UUID */
        AccountIdPath: string;
        /** @description Sync job UUID */
        JobIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example 0.2.0 */
                        version?: string;
                    };
                };
            };
        };
    };
    getToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Token issued successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description New access token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of cloud accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudAccountListResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudAccountCreate"];
            };
        };
        responses: {
            /** @description Cloud account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudAccountResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role (requires admin) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credential validation failed or invalid request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cloud account UUID */
                account_id: components["parameters"]["AccountIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role (requires admin) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadBillingFile: {
        parameters: {
            query: {
                /** @description Cloud account UUID to associate records with */
                account_id: string;
                /** @description Provider hint. Auto-detected from filename if not provided. */
                provider?: "aws" | "azure" | "gcp" | "alibaba";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Billing file (CSV, Parquet, or JSON)
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Ingestion result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResult"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role (requires analyst or higher) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cloud account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    triggerSync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cloud account UUID */
                account_id: components["parameters"]["AccountIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync job started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "sync_started",
                     *       "account_id": "550e8400-e29b-41d4-a716-446655440000",
                     *       "job_id": "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                     *     }
                     */
                    "application/json": components["schemas"]["SyncJobResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Insufficient role (requires engineer or admin) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cloud account not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSyncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sync job UUID */
                job_id: components["parameters"]["JobIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync job status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobStatus"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job not found or expired */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRecords: {
        parameters: {
            query?: {
                /** @description Page number for pagination */
                page?: components["parameters"]["PageParam"];
                /** @description Number of items per page */
                page_size?: components["parameters"]["PageSizeParam"];
                provider?: "aws" | "azure" | "gcp" | "alibaba";
                region_id?: string;
                service_name?: string;
                start_date?: string;
                end_date?: string;
                account_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated FOCUS records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        records?: components["schemas"]["FocusRecord"][];
                        total?: number;
                        page?: number;
                        page_size?: number;
                    };
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRecordEnrichment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enriched record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudCarbonRecord"];
                };
            };
            /** @description Record not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    runEnrichment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichmentRunRequest"];
            };
        };
        responses: {
            /** @description Enrichment job queued successfully */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "job_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                     *       "tenant_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "mode": "incremental",
                     *       "status": "queued",
                     *       "queued_at": "2026-04-01T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["EnrichmentRunResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Insufficient role (requires engineer or above) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getEnrichmentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID returned by POST /enrichment/run */
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentStatusResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Job not found or expired (24h TTL) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Redis unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getEnrichmentSummary: {
        parameters: {
            query: {
                /** @description Tenant UUID */
                tenant_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrichment summary statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "tenant_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "total_records_enriched": 48230,
                     *       "total_focus_records": 50000,
                     *       "coverage_pct": 96.46,
                     *       "total_co2e_kg": 12847.32,
                     *       "total_scope3_co2e_kg": 8921.44,
                     *       "scope3_pct_of_total": 69.44,
                     *       "total_water_litres": 23104.8,
                     *       "last_enriched_at": "2026-04-01T11:58:22Z",
                     *       "enrichment_version": "1.0.0"
                     *     }
                     */
                    "application/json": components["schemas"]["EnrichmentSummaryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listRecommendations: {
        parameters: {
            query?: {
                status?: "open" | "implemented" | "dismissed" | "snoozed";
                type?: string;
                provider?: string;
                region?: string;
                min_cost_impact?: number;
                min_co2e_impact?: number;
                sort_by?: "impact_score" | "cost" | "co2e" | "water";
                mode?: "cost" | "sustainability";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of recommendations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    runRecommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "cost_weight": 0.6,
                 *       "carbon_weight": 0.3,
                 *       "water_weight": 0.1
                 *     }
                 */
                "application/json": components["schemas"]["RecommendationRunRequest"];
            };
        };
        responses: {
            /** @description Recommendation job queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRunResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    recommendationsSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated recommendation statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationSummaryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateRecommendation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationPatchRequest"];
            };
        };
        responses: {
            /** @description Updated recommendation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    overviewReport: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
                provider?: string;
                mode?: "cost" | "sustainability";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    carbonReport: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
                provider?: string;
                granularity?: "daily" | "weekly" | "monthly";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Carbon report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarbonReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    waterReport: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
                provider?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Water report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterReportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    forecastReport: {
        parameters: {
            query?: {
                /** @description Comma-separated list of metrics to forecast */
                metrics?: string;
                horizon_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forecast results keyed by metric name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    naturalLanguageQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "question": "Which AWS regions have the highest carbon intensity this month?"
                 *     }
                 */
                "application/json": components["schemas"]["NLQueryRequest"];
            };
        };
        responses: {
            /** @description Query results with generated SQL and follow-up suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NLQueryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    costCarbonReport: {
        parameters: {
            query?: {
                start_date?: string;
                end_date?: string;
                provider?: string;
                granularity?: "daily" | "weekly" | "monthly";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost vs carbon correlation data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        period?: {
                            /** Format: date */
                            start?: string;
                            /** Format: date */
                            end?: string;
                        };
                        by_service?: {
                            service_name?: string;
                            service_category?: string;
                            /** Format: double */
                            cost_usd?: number;
                            /** Format: double */
                            co2e_kg?: number;
                            /** Format: double */
                            carbon_efficiency?: number;
                        }[];
                        by_region?: {
                            region?: string;
                            provider?: string;
                            /** Format: double */
                            cost_usd?: number;
                            /** Format: double */
                            co2e_kg?: number;
                        }[];
                        time_series?: {
                            /** Format: date */
                            date?: string;
                            /** Format: double */
                            cost_usd?: number;
                            /** Format: double */
                            co2e_kg?: number;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of policy rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyRule"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyRuleCreate"];
            };
        };
        responses: {
            /** @description Policy rule created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyRule"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of agent configurations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateAgentConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_type: "anomaly_detector" | "carbon_spike_monitor" | "rightsizing_agent" | "idle_reaper" | "green_scheduler";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigPatchRequest"];
            };
        };
        responses: {
            /** @description Updated agent configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    triggerAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_type: "anomaly_detector" | "carbon_spike_monitor" | "rightsizing_agent" | "idle_reaper" | "green_scheduler";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualRunRequest"];
            };
        };
        responses: {
            /** @description Agent run started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualRunResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAgentRuns: {
        parameters: {
            query?: {
                agent_type?: string;
                status?: "running" | "completed" | "failed";
                /** @description Page number for pagination */
                page?: components["parameters"]["PageParam"];
                /** @description Number of items per page */
                page_size?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of agent runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    approveAgentAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveActionRequest"];
            };
        };
        responses: {
            /** @description Action approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveActionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
